driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: true
  require_ruby_for_busser: false
  require_chef_for_busser: false
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_extra_flags: '--skip-tags=start'
  ignore_paths_from_root:
    - .git

verifier:
  root_path: /opt/verifier

platforms:
  - name: centos-7
    driver_config:
      image: "kitchen-centos"
      provision_command:
        - sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        - sed -ri 's/^#?UsePAM .*/UsePAM no/' /etc/ssh/sshd_config
      run_command: "/usr/sbin/init"
      privileged: true
      use_sudo: false

suites:
  - name: default
    provisioner:
      idempotency_test: false
      playbook: test/integration/default/default.yml
